/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_LT_SLASH = 3,
  anon_sym_SLASH_GT = 4,
  sym_tag_name = 5,
  anon_sym_EQ = 6,
  sym_attribute_name = 7,
  anon_sym_DQUOTE = 8,
  anon_sym_SQUOTE = 9,
  aux_sym_attribute_string_content_double_token1 = 10,
  aux_sym_attribute_string_content_single_token1 = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_BQUOTE = 18,
  aux_sym_string_token1 = 19,
  sym_number = 20,
  anon_sym_true = 21,
  anon_sym_false = 22,
  sym_property_key = 23,
  sym_identifier = 24,
  sym_operator = 25,
  anon_sym_LT_BANG_DASH_DASH = 26,
  anon_sym_DASH_DASH_GT = 27,
  sym_comment_content = 28,
  sym_text = 29,
  sym_document = 30,
  sym__node = 31,
  sym_element = 32,
  sym_start_tag = 33,
  sym_end_tag = 34,
  sym_self_closing_element = 35,
  sym__attribute = 36,
  sym_attribute = 37,
  sym_expression_attribute = 38,
  sym_quoted_attribute_value = 39,
  sym_attribute_string_content_double = 40,
  sym_attribute_string_content_single = 41,
  sym_expression_value = 42,
  sym_expression = 43,
  aux_sym__expression_inner = 44,
  sym__expression_token = 45,
  sym_object = 46,
  sym_array = 47,
  sym_paren_expression = 48,
  sym_string = 49,
  sym_boolean = 50,
  sym_comment = 51,
  aux_sym_document_repeat1 = 52,
  aux_sym_start_tag_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_attribute_string_content_double_token1] = "attribute_string_content_double_token1",
  [aux_sym_attribute_string_content_single_token1] = "attribute_string_content_single_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_string_token1] = "string_content",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_property_key] = "property_key",
  [sym_identifier] = "identifier",
  [sym_operator] = "operator",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_comment_content] = "comment_content",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_element] = "self_closing_element",
  [sym__attribute] = "_attribute",
  [sym_attribute] = "attribute",
  [sym_expression_attribute] = "expression_attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_attribute_string_content_double] = "attribute_string_content_double",
  [sym_attribute_string_content_single] = "attribute_string_content_single",
  [sym_expression_value] = "expression_value",
  [sym_expression] = "expression",
  [aux_sym__expression_inner] = "_expression_inner",
  [sym__expression_token] = "_expression_token",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_paren_expression] = "paren_expression",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_attribute_string_content_double_token1] = aux_sym_attribute_string_content_double_token1,
  [aux_sym_attribute_string_content_single_token1] = aux_sym_attribute_string_content_single_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_property_key] = sym_property_key,
  [sym_identifier] = sym_identifier,
  [sym_operator] = sym_operator,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_comment_content] = sym_comment_content,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_element] = sym_self_closing_element,
  [sym__attribute] = sym__attribute,
  [sym_attribute] = sym_attribute,
  [sym_expression_attribute] = sym_expression_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_attribute_string_content_double] = sym_attribute_string_content_double,
  [sym_attribute_string_content_single] = sym_attribute_string_content_single,
  [sym_expression_value] = sym_expression_value,
  [sym_expression] = sym_expression,
  [aux_sym__expression_inner] = aux_sym__expression_inner,
  [sym__expression_token] = sym__expression_token,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_paren_expression] = sym_paren_expression,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_string_content_double_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_string_content_single_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_property_key] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_element] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_string_content_double] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_string_content_single] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_value] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expression_inner] = {
    .visible = false,
    .named = false,
  },
  [sym__expression_token] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = aux_sym_string_token1,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 21,
        '\'', 22,
        '(', 31,
        ')', 32,
        '-', 3,
        '/', 7,
        '<', 14,
        '=', 19,
        '>', 15,
        '[', 29,
        ']', 30,
        '`', 33,
        'f', 41,
        't', 45,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 21,
        '\'', 22,
        '(', 31,
        ')', 32,
        '[', 29,
        ']', 30,
        '`', 33,
        'f', 41,
        't', 45,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (lookahead == '!' ||
          ('&' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '|') ADVANCE(50);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(51);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '>') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(52);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(54);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '<') ADVANCE(14);
      if (lookahead == '{') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_attribute_string_content_double_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_attribute_string_content_double_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_attribute_string_content_single_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_attribute_string_content_single_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_property_key);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == 'a') ADVANCE(44);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == 'e') ADVANCE(39);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == 'l') ADVANCE(46);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == 'r') ADVANCE(47);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == 's') ADVANCE(43);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == 'u') ADVANCE(42);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '!' ||
          lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '|') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment_content);
      if (lookahead == '-') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_comment_content);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(56);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 23},
  [43] = {.lex_state = 25},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 34},
  [50] = {.lex_state = 23},
  [51] = {.lex_state = 25},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 53},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_property_key] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(63),
    [sym__node] = STATE(25),
    [sym_element] = STATE(25),
    [sym_start_tag] = STATE(23),
    [sym_self_closing_element] = STATE(25),
    [sym_expression] = STATE(25),
    [sym_comment] = STATE(25),
    [aux_sym_document_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(9),
    [sym_text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(16), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(24), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(36), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(22), 3,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    ACTIONS(33), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(2), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [45] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(56), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(4), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [88] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(64), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(2), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [131] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(68), 1,
      anon_sym_RPAREN,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(70), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(8), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [174] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(76), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(10), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [217] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      sym_identifier,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(82), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(9), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [260] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(64), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(2), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [303] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(64), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(2), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [346] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_RBRACK,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(64), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(2), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [389] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(94), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(12), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [432] = 11,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(58), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(64), 3,
      sym_number,
      sym_property_key,
      sym_operator,
    STATE(2), 7,
      aux_sym__expression_inner,
      sym__expression_token,
      sym_object,
      sym_array,
      sym_paren_expression,
      sym_string,
      sym_boolean,
  [475] = 2,
    ACTIONS(102), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(100), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [495] = 2,
    ACTIONS(106), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(104), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [515] = 2,
    ACTIONS(110), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(108), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [535] = 2,
    ACTIONS(114), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(112), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [555] = 2,
    ACTIONS(118), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(116), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [575] = 2,
    ACTIONS(122), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(120), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [595] = 2,
    ACTIONS(126), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(124), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [615] = 2,
    ACTIONS(130), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(128), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [635] = 2,
    ACTIONS(134), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(132), 12,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
      sym_number,
      sym_property_key,
      sym_operator,
  [655] = 8,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(141), 1,
      anon_sym_LT_SLASH,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
    ACTIONS(146), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(149), 1,
      sym_text,
    STATE(23), 1,
      sym_start_tag,
    STATE(22), 6,
      sym__node,
      sym_element,
      sym_self_closing_element,
      sym_expression,
      sym_comment,
      aux_sym_document_repeat1,
  [685] = 8,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(152), 1,
      anon_sym_LT_SLASH,
    ACTIONS(154), 1,
      sym_text,
    STATE(23), 1,
      sym_start_tag,
    STATE(31), 1,
      sym_end_tag,
    STATE(24), 6,
      sym__node,
      sym_element,
      sym_self_closing_element,
      sym_expression,
      sym_comment,
      aux_sym_document_repeat1,
  [715] = 8,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(152), 1,
      anon_sym_LT_SLASH,
    ACTIONS(156), 1,
      sym_text,
    STATE(23), 1,
      sym_start_tag,
    STATE(34), 1,
      sym_end_tag,
    STATE(22), 6,
      sym__node,
      sym_element,
      sym_self_closing_element,
      sym_expression,
      sym_comment,
      aux_sym_document_repeat1,
  [745] = 7,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(156), 1,
      sym_text,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_start_tag,
    STATE(22), 6,
      sym__node,
      sym_element,
      sym_self_closing_element,
      sym_expression,
      sym_comment,
      aux_sym_document_repeat1,
  [772] = 4,
    ACTIONS(160), 1,
      anon_sym_GT,
    ACTIONS(162), 1,
      anon_sym_SLASH_GT,
    ACTIONS(164), 1,
      sym_attribute_name,
    STATE(27), 4,
      sym__attribute,
      sym_attribute,
      sym_expression_attribute,
      aux_sym_start_tag_repeat1,
  [788] = 4,
    ACTIONS(164), 1,
      sym_attribute_name,
    ACTIONS(166), 1,
      anon_sym_GT,
    ACTIONS(168), 1,
      anon_sym_SLASH_GT,
    STATE(28), 4,
      sym__attribute,
      sym_attribute,
      sym_expression_attribute,
      aux_sym_start_tag_repeat1,
  [804] = 3,
    ACTIONS(172), 1,
      sym_attribute_name,
    ACTIONS(170), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(28), 4,
      sym__attribute,
      sym_attribute,
      sym_expression_attribute,
      aux_sym_start_tag_repeat1,
  [818] = 2,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(177), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [829] = 2,
    ACTIONS(179), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(181), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [840] = 2,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(185), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [851] = 2,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(189), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [862] = 2,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(193), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [873] = 2,
    ACTIONS(195), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(197), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [884] = 2,
    ACTIONS(199), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(201), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [895] = 2,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(205), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [906] = 2,
    ACTIONS(209), 1,
      sym_text,
    ACTIONS(207), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [916] = 2,
    ACTIONS(213), 1,
      sym_text,
    ACTIONS(211), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [926] = 5,
    ACTIONS(215), 1,
      anon_sym_DQUOTE,
    ACTIONS(217), 1,
      anon_sym_SQUOTE,
    ACTIONS(219), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_quoted_attribute_value,
    STATE(45), 1,
      sym_expression_value,
  [942] = 2,
    ACTIONS(223), 1,
      anon_sym_EQ,
    ACTIONS(221), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [951] = 1,
    ACTIONS(225), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [957] = 3,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    ACTIONS(229), 1,
      aux_sym_attribute_string_content_double_token1,
    STATE(58), 1,
      sym_attribute_string_content_double,
  [967] = 3,
    ACTIONS(227), 1,
      anon_sym_SQUOTE,
    ACTIONS(231), 1,
      aux_sym_attribute_string_content_single_token1,
    STATE(60), 1,
      sym_attribute_string_content_single,
  [977] = 1,
    ACTIONS(233), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [983] = 1,
    ACTIONS(235), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [989] = 1,
    ACTIONS(237), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [995] = 1,
    ACTIONS(239), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1001] = 1,
    ACTIONS(241), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1007] = 2,
    ACTIONS(243), 1,
      anon_sym_BQUOTE,
    ACTIONS(245), 1,
      aux_sym_string_token1,
  [1014] = 2,
    ACTIONS(243), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      aux_sym_attribute_string_content_double_token1,
  [1021] = 2,
    ACTIONS(243), 1,
      anon_sym_SQUOTE,
    ACTIONS(249), 1,
      aux_sym_attribute_string_content_single_token1,
  [1028] = 1,
    ACTIONS(251), 1,
      sym_tag_name,
  [1032] = 1,
    ACTIONS(253), 1,
      anon_sym_DQUOTE,
  [1036] = 1,
    ACTIONS(255), 1,
      sym_tag_name,
  [1040] = 1,
    ACTIONS(257), 1,
      anon_sym_GT,
  [1044] = 1,
    ACTIONS(259), 1,
      anon_sym_DASH_DASH_GT,
  [1048] = 1,
    ACTIONS(261), 1,
      anon_sym_DQUOTE,
  [1052] = 1,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
  [1056] = 1,
    ACTIONS(265), 1,
      anon_sym_SQUOTE,
  [1060] = 1,
    ACTIONS(263), 1,
      anon_sym_SQUOTE,
  [1064] = 1,
    ACTIONS(267), 1,
      sym_comment_content,
  [1068] = 1,
    ACTIONS(253), 1,
      anon_sym_SQUOTE,
  [1072] = 1,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
  [1076] = 1,
    ACTIONS(253), 1,
      anon_sym_BQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 131,
  [SMALL_STATE(6)] = 174,
  [SMALL_STATE(7)] = 217,
  [SMALL_STATE(8)] = 260,
  [SMALL_STATE(9)] = 303,
  [SMALL_STATE(10)] = 346,
  [SMALL_STATE(11)] = 389,
  [SMALL_STATE(12)] = 432,
  [SMALL_STATE(13)] = 475,
  [SMALL_STATE(14)] = 495,
  [SMALL_STATE(15)] = 515,
  [SMALL_STATE(16)] = 535,
  [SMALL_STATE(17)] = 555,
  [SMALL_STATE(18)] = 575,
  [SMALL_STATE(19)] = 595,
  [SMALL_STATE(20)] = 615,
  [SMALL_STATE(21)] = 635,
  [SMALL_STATE(22)] = 655,
  [SMALL_STATE(23)] = 685,
  [SMALL_STATE(24)] = 715,
  [SMALL_STATE(25)] = 745,
  [SMALL_STATE(26)] = 772,
  [SMALL_STATE(27)] = 788,
  [SMALL_STATE(28)] = 804,
  [SMALL_STATE(29)] = 818,
  [SMALL_STATE(30)] = 829,
  [SMALL_STATE(31)] = 840,
  [SMALL_STATE(32)] = 851,
  [SMALL_STATE(33)] = 862,
  [SMALL_STATE(34)] = 873,
  [SMALL_STATE(35)] = 884,
  [SMALL_STATE(36)] = 895,
  [SMALL_STATE(37)] = 906,
  [SMALL_STATE(38)] = 916,
  [SMALL_STATE(39)] = 926,
  [SMALL_STATE(40)] = 942,
  [SMALL_STATE(41)] = 951,
  [SMALL_STATE(42)] = 957,
  [SMALL_STATE(43)] = 967,
  [SMALL_STATE(44)] = 977,
  [SMALL_STATE(45)] = 983,
  [SMALL_STATE(46)] = 989,
  [SMALL_STATE(47)] = 995,
  [SMALL_STATE(48)] = 1001,
  [SMALL_STATE(49)] = 1007,
  [SMALL_STATE(50)] = 1014,
  [SMALL_STATE(51)] = 1021,
  [SMALL_STATE(52)] = 1028,
  [SMALL_STATE(53)] = 1032,
  [SMALL_STATE(54)] = 1036,
  [SMALL_STATE(55)] = 1040,
  [SMALL_STATE(56)] = 1044,
  [SMALL_STATE(57)] = 1048,
  [SMALL_STATE(58)] = 1052,
  [SMALL_STATE(59)] = 1056,
  [SMALL_STATE(60)] = 1060,
  [SMALL_STATE(61)] = 1064,
  [SMALL_STATE(62)] = 1068,
  [SMALL_STATE(63)] = 1072,
  [SMALL_STATE(64)] = 1076,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(50),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(51),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(7),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expression_inner, 2, 0, 0),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(6),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(5),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(49),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(2),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(13),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression_inner, 2, 0, 0), SHIFT_REPEAT(2),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expression, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expression, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expression, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expression, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_attribute, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_string_content_double, 1, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_string_content_single, 1, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [269] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
