/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_LT_SLASH = 3,
  anon_sym_SLASH_GT = 4,
  sym_tag_name = 5,
  anon_sym_EQ = 6,
  sym_attribute_name = 7,
  anon_sym_DQUOTE = 8,
  anon_sym_SQUOTE = 9,
  aux_sym_attribute_string_content_double_token1 = 10,
  aux_sym_attribute_string_content_single_token1 = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  aux_sym_expression_content_token1 = 18,
  aux_sym_bracket_content_token1 = 19,
  anon_sym_BQUOTE = 20,
  aux_sym_string_token1 = 21,
  anon_sym_LT_BANG_DASH_DASH = 22,
  anon_sym_DASH_DASH_GT = 23,
  sym_comment_content = 24,
  sym_text = 25,
  sym_document = 26,
  sym__node = 27,
  sym_element = 28,
  sym_start_tag = 29,
  sym_end_tag = 30,
  sym_self_closing_element = 31,
  sym__attribute = 32,
  sym_attribute = 33,
  sym_expression_attribute = 34,
  sym_quoted_attribute_value = 35,
  sym_attribute_string_content_double = 36,
  sym_attribute_string_content_single = 37,
  sym_expression_value = 38,
  sym_expression = 39,
  sym_expression_content = 40,
  sym_bracket_content = 41,
  sym_string = 42,
  sym_comment = 43,
  aux_sym_document_repeat1 = 44,
  aux_sym_start_tag_repeat1 = 45,
  aux_sym_expression_content_repeat1 = 46,
  aux_sym_bracket_content_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_attribute_string_content_double_token1] = "attribute_string_content_double_token1",
  [aux_sym_attribute_string_content_single_token1] = "attribute_string_content_single_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_expression_content_token1] = "expression_content_token1",
  [aux_sym_bracket_content_token1] = "bracket_content_token1",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_comment_content] = "comment_content",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_element] = "self_closing_element",
  [sym__attribute] = "_attribute",
  [sym_attribute] = "attribute",
  [sym_expression_attribute] = "expression_attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_attribute_string_content_double] = "attribute_string_content_double",
  [sym_attribute_string_content_single] = "attribute_string_content_single",
  [sym_expression_value] = "expression_value",
  [sym_expression] = "expression",
  [sym_expression_content] = "expression_content",
  [sym_bracket_content] = "bracket_content",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_expression_content_repeat1] = "expression_content_repeat1",
  [aux_sym_bracket_content_repeat1] = "bracket_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_attribute_string_content_double_token1] = aux_sym_attribute_string_content_double_token1,
  [aux_sym_attribute_string_content_single_token1] = aux_sym_attribute_string_content_single_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_expression_content_token1] = aux_sym_expression_content_token1,
  [aux_sym_bracket_content_token1] = aux_sym_bracket_content_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_comment_content] = sym_comment_content,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_element] = sym_self_closing_element,
  [sym__attribute] = sym__attribute,
  [sym_attribute] = sym_attribute,
  [sym_expression_attribute] = sym_expression_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_attribute_string_content_double] = sym_attribute_string_content_double,
  [sym_attribute_string_content_single] = sym_attribute_string_content_single,
  [sym_expression_value] = sym_expression_value,
  [sym_expression] = sym_expression,
  [sym_expression_content] = sym_expression_content,
  [sym_bracket_content] = sym_bracket_content,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_expression_content_repeat1] = aux_sym_expression_content_repeat1,
  [aux_sym_bracket_content_repeat1] = aux_sym_bracket_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_string_content_double_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_string_content_single_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expression_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bracket_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_element] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_string_content_double] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_string_content_single] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_value] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_content] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bracket_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 17,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 46,
  [68] = 68,
  [69] = 66,
  [70] = 70,
  [71] = 54,
  [72] = 56,
  [73] = 64,
  [74] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 21,
        '$', 20,
        '\'', 22,
        '(', 31,
        ')', 32,
        '-', 4,
        '/', 7,
        '<', 13,
        '=', 19,
        '>', 14,
        '[', 29,
        ']', 30,
        '`', 37,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 21,
        '\'', 22,
        '(', 31,
        ')', 32,
        '[', 29,
        '`', 37,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '[') ADVANCE(29);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '`') ADVANCE(37);
      if (lookahead == '{') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '>') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(43);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '<') ADVANCE(13);
      if (lookahead == '{') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '_') ADVANCE(20);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_attribute_string_content_double_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_attribute_string_content_double_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_attribute_string_content_single_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_attribute_string_content_single_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_expression_content_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_expression_content_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_bracket_content_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_bracket_content_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment_content);
      if (lookahead == '-') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment_content);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 11},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 25},
  [39] = {.lex_state = 23},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 42},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 23},
  [57] = {.lex_state = 38},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 25},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 23},
  [73] = {.lex_state = 25},
  [74] = {.lex_state = 38},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(55),
    [sym__node] = STATE(5),
    [sym_element] = STATE(5),
    [sym_start_tag] = STATE(2),
    [sym_self_closing_element] = STATE(5),
    [sym_expression] = STATE(5),
    [sym_comment] = STATE(5),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(9),
    [sym_text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(26), 1,
      sym_end_tag,
    STATE(3), 6,
      sym__node,
      sym_element,
      sym_self_closing_element,
      sym_expression,
      sym_comment,
      aux_sym_document_repeat1,
  [30] = 8,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(28), 1,
      sym_end_tag,
    STATE(4), 6,
      sym__node,
      sym_element,
      sym_self_closing_element,
      sym_expression,
      sym_comment,
      aux_sym_document_repeat1,
  [60] = 8,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(24), 1,
      anon_sym_LT_SLASH,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(32), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(4), 6,
      sym__node,
      sym_element,
      sym_self_closing_element,
      sym_expression,
      sym_comment,
      aux_sym_document_repeat1,
  [90] = 7,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(4), 6,
      sym__node,
      sym_element,
      sym_self_closing_element,
      sym_expression,
      sym_comment,
      aux_sym_document_repeat1,
  [117] = 10,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      aux_sym_expression_content_token1,
    ACTIONS(51), 1,
      anon_sym_BQUOTE,
    STATE(59), 1,
      sym_expression_content,
    STATE(9), 2,
      sym_string,
      aux_sym_expression_content_repeat1,
  [149] = 10,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      aux_sym_expression_content_token1,
    ACTIONS(51), 1,
      anon_sym_BQUOTE,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_expression_content,
    STATE(9), 2,
      sym_string,
      aux_sym_expression_content_repeat1,
  [181] = 10,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      aux_sym_expression_content_token1,
    ACTIONS(51), 1,
      anon_sym_BQUOTE,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym_expression_content,
    STATE(9), 2,
      sym_string,
      aux_sym_expression_content_repeat1,
  [213] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_BQUOTE,
    ACTIONS(57), 1,
      aux_sym_expression_content_token1,
    ACTIONS(55), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(11), 2,
      sym_string,
      aux_sym_expression_content_repeat1,
  [243] = 10,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      aux_sym_expression_content_token1,
    ACTIONS(51), 1,
      anon_sym_BQUOTE,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_expression_content,
    STATE(9), 2,
      sym_string,
      aux_sym_expression_content_repeat1,
  [275] = 9,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      aux_sym_expression_content_token1,
    ACTIONS(81), 1,
      anon_sym_BQUOTE,
    ACTIONS(70), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(11), 2,
      sym_string,
      aux_sym_expression_content_repeat1,
  [305] = 10,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      aux_sym_expression_content_token1,
    ACTIONS(51), 1,
      anon_sym_BQUOTE,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_expression_content,
    STATE(9), 2,
      sym_string,
      aux_sym_expression_content_repeat1,
  [337] = 9,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      anon_sym_SQUOTE,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 1,
      anon_sym_LBRACK,
    ACTIONS(94), 1,
      aux_sym_bracket_content_token1,
    ACTIONS(96), 1,
      anon_sym_BQUOTE,
    STATE(50), 1,
      sym_bracket_content,
    STATE(15), 2,
      sym_string,
      aux_sym_bracket_content_repeat1,
  [366] = 9,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      anon_sym_SQUOTE,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 1,
      anon_sym_LBRACK,
    ACTIONS(94), 1,
      aux_sym_bracket_content_token1,
    ACTIONS(96), 1,
      anon_sym_BQUOTE,
    STATE(51), 1,
      sym_bracket_content,
    STATE(15), 2,
      sym_string,
      aux_sym_bracket_content_repeat1,
  [395] = 8,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      anon_sym_SQUOTE,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_BQUOTE,
    ACTIONS(98), 1,
      anon_sym_RBRACK,
    ACTIONS(100), 1,
      aux_sym_bracket_content_token1,
    STATE(19), 2,
      sym_string,
      aux_sym_bracket_content_repeat1,
  [421] = 2,
    ACTIONS(102), 1,
      aux_sym_expression_content_token1,
    ACTIONS(70), 8,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
  [435] = 2,
    ACTIONS(106), 1,
      aux_sym_expression_content_token1,
    ACTIONS(104), 8,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
  [449] = 2,
    ACTIONS(110), 1,
      aux_sym_expression_content_token1,
    ACTIONS(108), 8,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BQUOTE,
  [463] = 8,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(115), 1,
      anon_sym_SQUOTE,
    ACTIONS(118), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 1,
      anon_sym_RBRACK,
    ACTIONS(126), 1,
      aux_sym_bracket_content_token1,
    ACTIONS(129), 1,
      anon_sym_BQUOTE,
    STATE(19), 2,
      sym_string,
      aux_sym_bracket_content_repeat1,
  [489] = 4,
    ACTIONS(132), 1,
      anon_sym_GT,
    ACTIONS(134), 1,
      anon_sym_SLASH_GT,
    ACTIONS(136), 1,
      sym_attribute_name,
    STATE(22), 4,
      sym__attribute,
      sym_attribute,
      sym_expression_attribute,
      aux_sym_start_tag_repeat1,
  [505] = 4,
    ACTIONS(136), 1,
      sym_attribute_name,
    ACTIONS(138), 1,
      anon_sym_GT,
    ACTIONS(140), 1,
      anon_sym_SLASH_GT,
    STATE(20), 4,
      sym__attribute,
      sym_attribute,
      sym_expression_attribute,
      aux_sym_start_tag_repeat1,
  [521] = 3,
    ACTIONS(144), 1,
      sym_attribute_name,
    ACTIONS(142), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(22), 4,
      sym__attribute,
      sym_attribute,
      sym_expression_attribute,
      aux_sym_start_tag_repeat1,
  [535] = 2,
    ACTIONS(147), 1,
      aux_sym_bracket_content_token1,
    ACTIONS(124), 6,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BQUOTE,
  [547] = 2,
    ACTIONS(151), 1,
      aux_sym_bracket_content_token1,
    ACTIONS(149), 6,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BQUOTE,
  [559] = 2,
    ACTIONS(106), 1,
      aux_sym_bracket_content_token1,
    ACTIONS(104), 6,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BQUOTE,
  [571] = 2,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(155), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [582] = 2,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(159), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [593] = 2,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(163), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [604] = 2,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(167), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [615] = 2,
    ACTIONS(169), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(171), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [626] = 2,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(175), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [637] = 2,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(179), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [648] = 2,
    ACTIONS(181), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(183), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [659] = 5,
    ACTIONS(185), 1,
      anon_sym_DQUOTE,
    ACTIONS(187), 1,
      anon_sym_SQUOTE,
    ACTIONS(189), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_expression_value,
    STATE(41), 1,
      sym_quoted_attribute_value,
  [675] = 2,
    ACTIONS(193), 1,
      sym_text,
    ACTIONS(191), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [685] = 2,
    ACTIONS(197), 1,
      sym_text,
    ACTIONS(195), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LT_BANG_DASH_DASH,
  [695] = 2,
    ACTIONS(201), 1,
      anon_sym_EQ,
    ACTIONS(199), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [704] = 3,
    ACTIONS(203), 1,
      anon_sym_SQUOTE,
    ACTIONS(205), 1,
      aux_sym_attribute_string_content_single_token1,
    STATE(63), 1,
      sym_attribute_string_content_single,
  [714] = 3,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
    ACTIONS(207), 1,
      aux_sym_attribute_string_content_double_token1,
    STATE(61), 1,
      sym_attribute_string_content_double,
  [724] = 1,
    ACTIONS(209), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [730] = 1,
    ACTIONS(211), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [736] = 1,
    ACTIONS(213), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [742] = 1,
    ACTIONS(215), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [748] = 1,
    ACTIONS(217), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [754] = 1,
    ACTIONS(219), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [760] = 1,
    ACTIONS(221), 1,
      anon_sym_SQUOTE,
  [764] = 1,
    ACTIONS(223), 1,
      sym_tag_name,
  [768] = 1,
    ACTIONS(225), 1,
      sym_tag_name,
  [772] = 1,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
  [776] = 1,
    ACTIONS(227), 1,
      anon_sym_RBRACK,
  [780] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACK,
  [784] = 1,
    ACTIONS(231), 1,
      sym_comment_content,
  [788] = 1,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
  [792] = 1,
    ACTIONS(233), 1,
      anon_sym_BQUOTE,
  [796] = 1,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [800] = 1,
    ACTIONS(237), 1,
      aux_sym_attribute_string_content_double_token1,
  [804] = 1,
    ACTIONS(239), 1,
      aux_sym_string_token1,
  [808] = 1,
    ACTIONS(241), 1,
      anon_sym_GT,
  [812] = 1,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
  [816] = 1,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
  [820] = 1,
    ACTIONS(247), 1,
      anon_sym_DQUOTE,
  [824] = 1,
    ACTIONS(249), 1,
      anon_sym_SQUOTE,
  [828] = 1,
    ACTIONS(247), 1,
      anon_sym_SQUOTE,
  [832] = 1,
    ACTIONS(251), 1,
      aux_sym_attribute_string_content_single_token1,
  [836] = 1,
    ACTIONS(253), 1,
      anon_sym_RBRACE,
  [840] = 1,
    ACTIONS(233), 1,
      anon_sym_DQUOTE,
  [844] = 1,
    ACTIONS(233), 1,
      anon_sym_SQUOTE,
  [848] = 1,
    ACTIONS(255), 1,
      anon_sym_DASH_DASH_GT,
  [852] = 1,
    ACTIONS(221), 1,
      anon_sym_DQUOTE,
  [856] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
  [860] = 1,
    ACTIONS(221), 1,
      anon_sym_BQUOTE,
  [864] = 1,
    ACTIONS(257), 1,
      aux_sym_attribute_string_content_double_token1,
  [868] = 1,
    ACTIONS(259), 1,
      aux_sym_attribute_string_content_single_token1,
  [872] = 1,
    ACTIONS(261), 1,
      aux_sym_string_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 117,
  [SMALL_STATE(7)] = 149,
  [SMALL_STATE(8)] = 181,
  [SMALL_STATE(9)] = 213,
  [SMALL_STATE(10)] = 243,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 305,
  [SMALL_STATE(13)] = 337,
  [SMALL_STATE(14)] = 366,
  [SMALL_STATE(15)] = 395,
  [SMALL_STATE(16)] = 421,
  [SMALL_STATE(17)] = 435,
  [SMALL_STATE(18)] = 449,
  [SMALL_STATE(19)] = 463,
  [SMALL_STATE(20)] = 489,
  [SMALL_STATE(21)] = 505,
  [SMALL_STATE(22)] = 521,
  [SMALL_STATE(23)] = 535,
  [SMALL_STATE(24)] = 547,
  [SMALL_STATE(25)] = 559,
  [SMALL_STATE(26)] = 571,
  [SMALL_STATE(27)] = 582,
  [SMALL_STATE(28)] = 593,
  [SMALL_STATE(29)] = 604,
  [SMALL_STATE(30)] = 615,
  [SMALL_STATE(31)] = 626,
  [SMALL_STATE(32)] = 637,
  [SMALL_STATE(33)] = 648,
  [SMALL_STATE(34)] = 659,
  [SMALL_STATE(35)] = 675,
  [SMALL_STATE(36)] = 685,
  [SMALL_STATE(37)] = 695,
  [SMALL_STATE(38)] = 704,
  [SMALL_STATE(39)] = 714,
  [SMALL_STATE(40)] = 724,
  [SMALL_STATE(41)] = 730,
  [SMALL_STATE(42)] = 736,
  [SMALL_STATE(43)] = 742,
  [SMALL_STATE(44)] = 748,
  [SMALL_STATE(45)] = 754,
  [SMALL_STATE(46)] = 760,
  [SMALL_STATE(47)] = 764,
  [SMALL_STATE(48)] = 768,
  [SMALL_STATE(49)] = 772,
  [SMALL_STATE(50)] = 776,
  [SMALL_STATE(51)] = 780,
  [SMALL_STATE(52)] = 784,
  [SMALL_STATE(53)] = 788,
  [SMALL_STATE(54)] = 792,
  [SMALL_STATE(55)] = 796,
  [SMALL_STATE(56)] = 800,
  [SMALL_STATE(57)] = 804,
  [SMALL_STATE(58)] = 808,
  [SMALL_STATE(59)] = 812,
  [SMALL_STATE(60)] = 816,
  [SMALL_STATE(61)] = 820,
  [SMALL_STATE(62)] = 824,
  [SMALL_STATE(63)] = 828,
  [SMALL_STATE(64)] = 832,
  [SMALL_STATE(65)] = 836,
  [SMALL_STATE(66)] = 840,
  [SMALL_STATE(67)] = 844,
  [SMALL_STATE(68)] = 848,
  [SMALL_STATE(69)] = 852,
  [SMALL_STATE(70)] = 856,
  [SMALL_STATE(71)] = 860,
  [SMALL_STATE(72)] = 864,
  [SMALL_STATE(73)] = 868,
  [SMALL_STATE(74)] = 872,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_content, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_content, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_content_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_content_repeat1, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_content_repeat1, 3, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bracket_content_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bracket_content_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bracket_content_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bracket_content_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_bracket_content_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bracket_content_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bracket_content_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bracket_content_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_bracket_content_repeat1, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bracket_content_repeat1, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 4, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_attribute, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 3, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_string_content_double, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_string_content_single, 1, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
